library(sqldf)

db<-dbConnect(SQLite(),dbname="olympics.sqlite")

dbWriteTable(conn = db,name="bolt",value = bolt_df)
dbWriteTable(conn = db,name="gatlin",value = gatlin_df)
dbWriteTable(conn = db,name="olympics",value = olympic_df)
dbWriteTable(conn = db,name="phelps",value = phelps_df)
dbWriteTable(conn = db,name="opening_ceremony",value = opening_ceremony_df)
dbWriteTable(conn = db,name="allyson",value = allyson_df)
dbWriteTable(conn = db,name="ashton",value = ashton_df)
dbWriteTable(conn = db,name="biles",value = biles_df)
dbWriteTable(conn = db,name="blake",value = blake_df)
dbWriteTable(conn = db,name="katie",value = katie_df)
dbWriteTable(conn = db,name="kayla",value = kayla_df)
dbWriteTable(conn = db,name="ryan",value = ryan_df)
dbWriteTable(conn = db,name="wayne",value = wayne_df)
dbWriteTable(conn = db,name="adam",value = adam_df)
dbWriteTable(conn = db,name="bowie",value = bowie_df)
dbWriteTable(conn = db,name="brianna",value = brianna_df)
dbWriteTable(conn = db,name="christian",value = christian_df)
dbWriteTable(conn = db,name="dipa",value = dipa_df)
dbWriteTable(conn = db,name="elaine",value = elaine_df)
dbWriteTable(conn = db,name="fabio",value = fabio_df)
dbWriteTable(conn = db,name="haley",value = haley_df)
dbWriteTable(conn = db,name="jake",value = jake_df)
dbWriteTable(conn = db,name="jeff",value = jeff_df)
dbWriteTable(conn = db,name="jemima",value = jemima_df)
dbWriteTable(conn = db,name="mo",value = mo_df)
dbWriteTable(conn = db,name="murray",value = murray_df)
dbWriteTable(conn = db,name="neymar",value = neymar_df)
dbWriteTable(conn = db,name="nia",value = nia_df)
dbWriteTable(conn = db,name="omar",value = omar_df)
dbWriteTable(conn = db,name="sakshi",value = sakshi_df)
dbWriteTable(conn = db,name="whitlock",value = whitlock_df)
dbWriteTable(conn = db,name="derek",value = derek_df)

dbWriteTable(conn = db,name="closing_ceremony",value = closing_ceremony_df)
dbWriteTable(conn = db,name="erica",value = erica_df)
dbWriteTable(conn = db,name="grasse",value = grasse_df)
dbWriteTable(conn = db,name="shaunae",value = shaunae_df)
dbWriteTable(conn = db,name="sindhu",value = sindhu_df)



dbListTables(db)
dbDisconnect(db)
